### ISSUE TITLE
making Pi

### ISSUE THREAD

**Issue by zanuka** [zanuka/navigate#3]
### process for creating new NavPi images

- [ ] make sure latest daemon is installed
- [ ] sync chain
- [ ] kill daemon
- [ ] update OS
- [ ] update UI
- [ ] delete wallet.dat
- [ ] clear bash history
- [ ] shut down
- [ ] make image
- [ ] flash image onto card
- [ ] boot image
- [ ] wait for the daemon to fire up
- [ ] record the primary address shown in UI
- [ ] wipe card
- [ ] reflash image onto card
- [ ] boot into UI
- [ ] make sure primary address is different
- [ ] shrink image size if required (8GB or less in size)
- [ ] clear bash history 

**SHIP IT**

**Comment by matt-auckland** [comment]
Looks good

[ ] Shrink image size if required (Aim for 8GB or less in size) <- Can be required if you played around with partitions
[ ] Clear Bash history - `cat /dev/null >> /home/pi/.bash_history && history -c && exit` will do this and clear the current terminal session's history

**Comment by zanuka** [comment]
thanks @matt-auckland 🏅
